POST http://localhost:3001/api/services
Content-Type: application/json

{
  "name": "Food Court",
  "description": "Multiple restaurants and fast-food outlets offering a wide variety of cuisines.",
  "isAvailable": true
}